service: betterfield-resources-dapp-backend
frameworkVersion: '3'

plugins:
 - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 20

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'
